# Generated by Django 5.2.3 on 2025-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='name',
            new_name='text_1',
        ),
        migrations.AddField(
            model_name='feature',
            name='text_2',
            field=models.CharField(default='Default text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='text_3',
            field=models.CharField(default='Defaul text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='text_4',
            field=models.CharField(default='Default text', max_length=100),
            preserve_default=False,
        ),
    ]
