# Generated by Django 5.2.3 on 2025-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_name_feature_text_1_feature_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
