# Generated by Django 5.2.3 on 2025-06-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_subscription_stripe_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='text_1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='text_3',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='text_4',
        ),
    ]
