# Generated by Django 5.2.3 on 2025-06-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_text_1_feature_text_remove_feature_text_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
